Repository OCA/calendar, pull requests merged in 2021-11, with the labels that each got.

#57 [12.0][FIX] resource_booking : previous/next
  resource_booking/templates/portal.xml
Labels: approved, ready to merge, bot is merging ⏳

#58 [13.0][FIX] resource_booking : previous/next
  resource_booking/templates/portal.xml
Labels: bot is merging ⏳

#59 [IMP] resource_booking: faster tests
  resource_booking/tests/common.py
  resource_booking/tests/test_backend.py
Labels: bot is merging ⏳

#60 [FIX] Avoid sending notifications when public user
  resource_booking/models/calendar_event.py
Labels: bug, bot is merging ⏳

#61 [12.0][IMP]resource_booking: add test
  resource_booking/tests/test_portal.py
Labels: bot is merging ⏳
