Repository OCA/calendar, pull requests merged in 2021-07, with the labels that each got.

#31 [IMP] Apply copier template
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  setup/.setuptools-odoo-make-default-ignore
  setup/README
Labels: bot is merging ⏳

#33 [IMP] resource_booking: simplified time format
  resource_booking/templates/portal.xml
  resource_booking/tests/test_portal.py
Labels: approved, bot is merging ⏳

#12 [12.0][ADD] - add a link between project tasks and calendar events
  calendar_event_link_base/README.rst
  calendar_event_link_base/__init__.py
  calendar_event_link_base/__manifest__.py
  calendar_event_link_base/models/__init__.py
  calendar_event_link_base/models/calendar_event_link_mixin.py
  calendar_event_link_base/readme/CONTRIBUTORS.rst
  calendar_event_link_base/readme/DESCRIPTION.rst
  calendar_event_link_base/readme/USAGE.rst
  calendar_event_link_base/static/description/index.html
  calendar_event_link_project_task/README.rst
  calendar_event_link_project_task/__init__.py
  calendar_event_link_project_task/__manifest__.py
  calendar_event_link_project_task/models/__init__.py
  calendar_event_link_project_task/models/project_task.py
  calendar_event_link_project_task/readme/CONTRIBUTORS.rst
  calendar_event_link_project_task/readme/DESCRIPTION.rst
  calendar_event_link_project_task/static/description/index.html
  calendar_event_link_project_task/tests/__init__.py
  calendar_event_link_project_task/tests/test_calendar_event_link.py
  calendar_event_link_project_task/views/project_task.xml
  setup/calendar_event_link_base/odoo/addons/calendar_event_link_base
  setup/calendar_event_link_base/setup.py
  setup/calendar_event_link_project_task/odoo/addons/calendar_event_link_project_task
  setup/calendar_event_link_project_task/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#32 [MIG] resource_booking: migrate to v13
  oca_dependencies.txt
  resource_booking/README.rst
  resource_booking/__init__.py
  resource_booking/__manifest__.py
  resource_booking/controllers/__init__.py
  resource_booking/controllers/portal.py
  resource_booking/demo/res_users_demo.xml
  resource_booking/i18n/es.po
  resource_booking/i18n/resource_booking.pot
  resource_booking/migrations/13.0.1.0.0/noupdate_changes.xml
  resource_booking/migrations/13.0.1.0.0/post-migrate.py
  resource_booking/models/__init__.py
  resource_booking/models/calendar_event.py
  resource_booking/models/resource_booking.py
  resource_booking/models/resource_booking_combination.py
  resource_booking/models/resource_booking_type.py
  resource_booking/models/resource_booking_type_combination_rel.py
  resource_booking/models/resource_calendar.py
  resource_booking/models/resource_resource.py
  resource_booking/readme/CONFIGURE.rst
  resource_booking/readme/CONTRIBUTORS.rst
  resource_booking/readme/DESCRIPTION.rst
  resource_booking/readme/INSTALL.rst
  resource_booking/readme/ROADMAP.rst
  resource_booking/readme/USAGE.rst
  resource_booking/security/ir.model.access.csv
  resource_booking/security/resource_booking_security.xml
  resource_booking/static/description/icon.png
  resource_booking/static/description/icon.svg
  resource_booking/static/description/index.html
  resource_booking/static/src/css/portal.scss
  resource_booking/templates/assets.xml
  resource_booking/templates/portal.xml
  resource_booking/tests/__init__.py
  resource_booking/tests/common.py
  resource_booking/tests/test_backend.py
  resource_booking/tests/test_portal.py
  resource_booking/views/calendar_event_views.xml
  resource_booking/views/menus.xml
  resource_booking/views/resource_booking_combination_views.xml
  resource_booking/views/resource_booking_type_views.xml
  resource_booking/views/resource_booking_views.xml
  setup/resource_booking/odoo/addons/resource_booking
  setup/resource_booking/setup.py
  test-requirements.txt
Labels: bot is merging ⏳, migration, needs review

#34 [IMP+FIX] resource_booking: duration, location, involves me, hr_holidays_public
  resource_booking/__manifest__.py
  resource_booking/controllers/portal.py
  resource_booking/migrations/13.0.2.0.0/pre-migrate.py
  resource_booking/models/resource_booking.py
  resource_booking/models/resource_booking_combination.py
  resource_booking/models/resource_booking_type.py
  resource_booking/readme/CONFIGURE.rst
  resource_booking/readme/USAGE.rst
  resource_booking/templates/portal.xml
  resource_booking/tests/test_backend.py
  resource_booking/views/resource_booking_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#35 [FIX] resource_booking: error when recurrent meetings exist
  resource_booking/views/resource_booking_views.xml
Labels: approved, bot is merging ⏳, bug

#36 [FIX] resource_booking: access error on normal calendar
  resource_booking/views/calendar_event_views.xml
Labels: approved, bot is merging ⏳, bug

#38 [FIX] resource_booking: allow combination with other kind of leaves
  resource_booking/models/resource_calendar.py
  resource_booking/tests/test_backend.py
Labels: approved, bot is merging ⏳, bug

#39 [FIX] resource_booking: display location and duration on portal
  resource_booking/templates/portal.xml
  resource_booking/tests/test_portal.py
Labels: approved, bot is merging ⏳, bug

#40 [IMP] resource_booking: improve auto-assignment readability
  resource_booking/views/resource_booking_views.xml
Labels: approved, bot is merging ⏳, enhancement

#37 [IMP] resource_booking: autoconfirm preselected combination resource attendees
  resource_booking/controllers/portal.py
  resource_booking/models/calendar_event.py
  resource_booking/tests/test_backend.py
Labels: approved, bot is merging ⏳, enhancement

#41 [IMP] resource_booking: add organizer
  resource_booking/models/resource_booking.py
  resource_booking/tests/test_backend.py
  resource_booking/views/resource_booking_views.xml
Labels: approved, bot is merging ⏳, enhancement
