Repository OCA/calendar, pull requests merged in 2023-09, with the labels that each got.

#79 [14.0][IMP] add tests assigning multiple human resources
  resource_booking/tests/test_backend.py
Labels: bot is merging ⏳

#100 [15.0][IMP] resource_booking: Allow a booking to span more than one calendar day
  resource_booking/models/resource_booking.py
  resource_booking/tests/common.py
  resource_booking/tests/test_backend.py
Labels: approved, ready to merge, bot is merging ⏳

#104 [15.0][FIX] resource_booking: Add class to schedule page to show full dropdown if opened at the bottom
  resource_booking/static/src/scss/portal.scss
  resource_booking/templates/portal.xml
Labels: approved
