Repository OCA/calendar, pull requests merged in 2024-06, with the labels that each got.

#124 [15.0][ADD] calendar_export_ics
  calendar_export_ics/README.rst
  calendar_export_ics/__init__.py
  calendar_export_ics/__manifest__.py
  calendar_export_ics/readme/CONTRIBUTORS.rst
  calendar_export_ics/readme/DESCRIPTION.rst
  calendar_export_ics/readme/USAGE.rst
  calendar_export_ics/security/calendar_export_security.xml
  calendar_export_ics/security/ir.model.access.csv
  calendar_export_ics/static/description/index.html
  calendar_export_ics/tests/__init__.py
  calendar_export_ics/tests/test_calendar_export_ics.py
  calendar_export_ics/wizards/__init__.py
  calendar_export_ics/wizards/wizard_export_ics.py
  calendar_export_ics/wizards/wizard_export_ics.xml
  setup/calendar_export_ics/odoo/addons/calendar_export_ics
  setup/calendar_export_ics/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#127 [16.0][IMP] resource_booking: Add support for mail_note subtype by default
  resource_booking/models/calendar_event.py
  resource_booking/tests/test_backend.py
Labels: bot is merging ⏳

#129 [16.0][IMP] resource_booking: Add support for mail_note subtype by default
  resource_booking/models/calendar_event.py
  resource_booking/tests/test_backend.py
Labels: bot is merging ⏳

#130 [16.0][FIX] resource_booking: Change combination_id mandatory when autoassign is false
  resource_booking/tests/test_backend.py
  resource_booking/views/resource_booking_views.xml
Labels: approved, bot is merging ⏳

#131 [15.0][FIX] resource_booking: Change combination_id mandatory when autoassign is false
  resource_booking/tests/test_backend.py
  resource_booking/views/resource_booking_views.xml
Labels: bot is merging ⏳
