Repository OCA/calendar, pull requests merged in 2024-05, with the labels that each got.

#108 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .oca_hooks.cfg
  .pre-commit-config.yaml
  resource_booking/i18n/fr.po
  resource_booking/i18n/resource_booking.pot
Labels: help wanted, needs review, bot is merging ⏳

#123 [16.0][FIX] resource_booking: Two fields with same label Activities
  resource_booking/i18n/es.po
  resource_booking/i18n/resource_booking.pot
  resource_booking/models/resource_booking.py
Labels: bot is merging ⏳

#121 [16.0][FIX] resource_booking: Add booking_count to portal values only if requested
  resource_booking/controllers/portal.py
Labels: bot is merging ⏳

#125 [16.0][IMP] resource_booking: Add priority to portal_my_home view to prevent side effects in some cases
  resource_booking/templates/portal.xml
Labels: approved, bot is merging ⏳

#126 [16.0][FIX] resource_booking: Avoid the error if a message is written from portal.
  resource_booking/models/resource_booking.py
Labels: approved, bot is merging ⏳
